# Generated by Django 4.2.25 on 2025-12-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_lead_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="first_response_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="responded",
            field=models.BooleanField(default=False),
        ),
    ]
