# Generated by Django 4.2.25 on 2025-12-31 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leads", "0003_lead_first_response_at_lead_responded"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="first_response_at",
            new_name="reminder_at",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="conversation",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="message",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="responded",
        ),
        migrations.AddField(
            model_name="lead",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("interested", "Interested"),
                    ("not_interested", "Not Interested"),
                    ("call_later", "Call Later"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
