# Generated by Django 4.2.25 on 2026-01-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_address_alter_order_buyer_and_more"),
        ("leads", "0006_alter_lead_buyer_alter_lead_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("interested", "Interested"),
                    ("converted", "Converted to Order"),
                    ("not_interested", "Not Interested"),
                    ("call_later", "Call Later"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
