# Generated by Django 4.2.25 on 2025-12-31 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_moq_sellercategory_product_seller_category"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productanalytics",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="products.product",
            ),
        ),
    ]
