# Generated by Django 4.2.25 on 2025-12-31 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_moq_sellercategory_product_seller_category"),
        ("analytics", "0002_alter_productanalytics_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productview",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="products.product",
            ),
        ),
    ]
