# Generated by Django 4.2.25 on 2025-12-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_profile_location_profile_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
