# Generated by Django 4.2.25 on 2025-12-30 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0006_sellerverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerverification",
            name="seller",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_verification",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
