# Generated by Django 4.2.25 on 2025-12-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_sellerverification_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellerverification",
            name="address_proof",
        ),
        migrations.AddField(
            model_name="sellerverification",
            name="gst_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="verification/gst_certificate/"
            ),
        ),
    ]
