# Generated by Django 4.2.25 on 2026-01-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_sellerverification_address_proof_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="profile_image",
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AN", "Andaman & Nicobar"),
                    ("AP", "Andhra Pradesh"),
                    ("AR", "Arunachal Pradesh"),
                    ("AS", "Assam"),
                    ("BR", "Bihar"),
                    ("CG", "Chhattisgarh"),
                    ("DL", "Delhi"),
                    ("GA", "Goa"),
                    ("GJ", "Gujarat"),
                    ("HR", "Haryana"),
                    ("HP", "Himachal Pradesh"),
                    ("JH", "Jharkhand"),
                    ("KA", "Karnataka"),
                    ("KL", "Kerala"),
                    ("MP", "Madhya Pradesh"),
                    ("MH", "Maharashtra"),
                    ("OR", "Odisha"),
                    ("PB", "Punjab"),
                    ("RJ", "Rajasthan"),
                    ("TN", "Tamil Nadu"),
                    ("TS", "Telangana"),
                    ("UP", "Uttar Pradesh"),
                    ("UK", "Uttarakhand"),
                    ("WB", "West Bengal"),
                ],
                max_length=5,
            ),
        ),
    ]
