# Generated by Django 4.2.25 on 2025-12-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
