# Generated by Django 4.2.25 on 2025-12-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_by_seller",
            field=models.BooleanField(default=False),
        ),
    ]
