# Generated by Django 4.2.25 on 2025-12-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_category_name_alter_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="created_by_seller",
        ),
        migrations.AlterField(
            model_name="product",
            name="location",
            field=models.CharField(max_length=100),
        ),
    ]
