# Generated by Django 4.2.25 on 2025-12-31 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0007_remove_category_created_by_seller_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="moq",
            field=models.PositiveIntegerField(
                default=1, help_text="Minimum order quantity"
            ),
        ),
        migrations.CreateModel(
            name="SellerCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="seller_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.sellercategory",
            ),
        ),
    ]
